In [1]:
import torch
import pandas as pd

In [2]:
df = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
meta = torch.tensor(df.values[0])
meta

tensor([1, 2, 3])

In [6]:
# metaに要素を追加
meta = torch.cat([meta, torch.tensor([10])])
meta

tensor([ 1,  2,  3, 10])

In [9]:
import torch.nn as nn

In [16]:
input = torch.randn(1, 5)
print(input)

tensor([[ 0.7512, -0.1444, -2.6293,  0.3104,  2.9045]])


In [18]:
softmax = nn.Softmax(dim=1)
print(softmax(input))

tensor([[0.0935, 0.0382, 0.0032, 0.0601, 0.8050]])


In [20]:
res = torch.argmax(softmax(input)).item()
res

4

In [21]:
type(res)

int